livekit/livekit-cli

go.mod, pkg/loadtester/loadtest.go, pkg/loadtester/loadtester.go, pkg/loadtester/stats.go
Output errors in summary:
```
Summary | Tester | Tracks | Bitrate                 | Latency | Total Dropped | Error
| Sub 0  | 2/0    | 175.0kbps               |  -      | 0 (0%)        | -
| Sub 1  | 2/0    | 150.9kbps               |  -      | 0 (0%)        | -
| Sub 2  | 2/0    | 152.0kbps               |  -      | 0 (0%)        | -
| Sub 3  | 2/0    | 151.2kbps               |  -      | 0 (0%)        | -
| Sub 4  | 2/0    | 149.0kbps               |  -      | 0 (0%)        | -
| Sub 5  | 2/0    | 149.0kbps               |  -      | 0 (0%)        | -
| Sub 6  | 2/0    | 134.8kbps               |  -      | 0 (0%)        | -
| Sub 7  | 2/0    | 133.9kbps               |  -      | 0 (0%)        | -
| Sub 8  | 2/0    | 134.2kbps               |  -      | 0 (0%)        | -
| Sub 9  | 2/0 …
```
=> don't abort test on a single tester error

.github/workflows/release.yml
This PR intends to fix issue #27 where an error occured in v0.8.0 because the build doesn't pull the LFS files in `pkg/provider/resources`.
In order to solve this problem, we just have to tell the workflow in `.github/workflows/release.yml` to download the LFS files so it's included in the build. But, there's a currently ongoing issue with the LFS that you can see [here](https://github.com/actions/checkout/issues/270).
You can see the sample release files from the updated release.yml [in my fork](https://github.com/stevenhansel/livekit-cli/releases/tag/v0.8.1)
=> Update release.yml to dereference files from Git LFS

README.md, cmd/livekit-cli/join.go, cmd/livekit-cli/join_test.go
Adds support for TCP sockets.
Using a new format for the "name" string passed in via `--publish`
The format is `mime_type://address:port` in the case of TCP or `mime_type:://unix_socket/path` in the case of unix sockets
The existence of the second `:` in the string is used to assume a TCP endpoint in the address:port format.
=> Support TCP sockets in addition to Unix sockets

cmd/livekit-cli/egress.go, cmd/livekit-cli/ingress.go, cmd/livekit-cli/join.go, cmd/livekit-cli/loadtest.go, cmd/livekit-cli/main.go, cmd/livekit-cli/project.go, cmd/livekit-cli/room.go, cmd/livekit-cli/token.go, cmd/livekit-cli/utils.go, go.mod, go.sum, pkg/config/config.go
Instead of having to pass in connection details or rely on a fixed set of environment variables, the project subcommand would save multiple connetion details in ~/.livekit/cli-config.yaml.
The design of the CLI takes inspiration from kubectl, where all commands are able to take in a `--project` flag and automatically use details from that project.
listing projects
```
% ./bin/livekit-cli project list
+------------+-----------------------------+--------------------------+---------+
|    NAME    |             URL             |         API KEY          | DEFAULT |
+------------+-----------------------------+--------------------------+---------+
| my-server  | https://my-server.host.com  | API012348rquKztZEoZJVabc | true    |
| local      | http://localhost:7880       | devkey …
```
=> Introducing `project` subcommand

install-cli.sh
uname exists in /bin on Ubuntu.  As such, the installation fails.               
The script determines the OS without specifying the complete path to uname.  Do  the same in order to determine ARCH.
=> don't assume uname in /usr/bin/

pkg/loadtester/loadtest.go
Previously, a generated random room name hasn't been printed. This small change fixes that.
**Before**
```
$ livekit-cli load-test --audio-publishers 32 --subscribers 32 [skipped connection params]
Starting load test with 32 audio publishers, 32 subscribers, room: 
publishing audio track - domji_pub_0
```
**After**
```
$ livekit-cli load-test --audio-publishers 32 --subscribers 32 [skipped connection params]
Starting load test with 32 audio publishers, 32 subscribers, room: testroom405
publishing audio track - sqksj_pub_0
```
=> Fix stale room name in load test

cmd/livekit-cli/egress.go, cmd/livekit-cli/loadtest.go, go.mod, go.sum, pkg/loadtester/loadtest.go, pkg/loadtester/loadtester.go, pkg/loadtester/speakersimulator.go
`load-test` now takes in a `--simulate-speakers` flag to randomly rotate publishers to speak
=> Simulate rotating speakers with load-test and test-egress-template

README.md
This is a super small docs PR: When running the current git command, the result is `fatal: repository 'github.com/livekit/livekit-cli' does not exist`. I've followed the example from https://github.com/livekit/livekit/blob/master/README.md#building-from-source and added the `https://` prefix.
=> Update git command in README

Dockerfile
- remove `GO111MODULE` as it is default for go build now
- pin the alpine tag to the latest release `3.19`
cc @Sean-Der
=> chore: improve dockerfile

.goreleaser.yaml
update ldflags to include `-s -w` to strip the symbol table and DWARF debug information.
cc @Sean-Der
=> goreleaser: improve binary artifact size

install-cli.sh
sudo should be called when moving the file, not when unarchiving. 
- fixes #324  
- fixes #327
verified to work. here's the output:
```
󰘎  bash install-cli.sh
sudo is required to install to /usr/local/bin
Installing livekit-cli 1.4.3
Downloading from https://github.com/livekit/livekit-cli/releases/download/v1.4.3/livekit-cli_1.4.3_linux_amd64.tar.gz...
[sudo] password for esskayesss:
livekit-cli is installed to /usr/local/bin
```
=> Fix: Correct sudo usage during installation

version.go
patch to version to match with 1.5.0 release
relates to https://github.com/Homebrew/homebrew-core/pull/175433
=> bump version for 1.5.1 release

cmd/livekit-cli/proto.go, cmd/livekit-cli/sip.go, cmd/livekit-cli/utils.go
Support new SIP Inbound/Outbound Trunk API and move all SIP commands into a separate cli tree:
- `list-sip-trunk` -> `sip trunk list`
- `list-sip-dispatch-rule` -> `sip dispatch list`
- `create-sip-participant` -> `sip participant create`
Old commands continue to work, they are only hidden from the CLI help.
I also renamed the columns for legacy trunks list command. Now they match names in new API (`OutboundNumber` -> `Number`, `InboundNumbers` -> `AllowedNumbers`). 
Requires https://github.com/livekit/protocol/pull/738
=> Support new SIP Trunk API. Move to subcommands.

.goreleaser.yaml
Unless specified, Goreleaser will use the repo name in the filename of archives. This makes it use the "lk_" prefix
=> fix(build): fix name templating for release archives

install-cli.sh
- Linux build script is aware of new `lk` binary name
- Symlinks old `livekit-cli` name on install
> [!WARNING]
> Merge after https://github.com/livekit/livekit-cli/pull/343
=> chore(build): update linux build script

cmd/lk/proto.go
We need to push out a hotfix due to breakage. I was trying the SIP guide and it failed on the first example.
=> Fix logic error prevent request.json from functioning

cmd/lk/room.go, cmd/lk/utils.go
- Fixes #361, and adds back legacy `--room` functionality
- Makes sure to thread the main Context through room API calls, so that they are properly cancellable
=> fix(cmd): read room name from cmd args

Makefile, cmd/lk/main.go, pkg/config/config.go
- Fixes erroneous file permission check on config directory
- Explicit build targets to make it simpler to build in Windows
- Deprecation check is now aware of Windows executable name
https://linear.app/livekit/issue/CLT-560/cli-error-config-file-cusersgrafhlivekitcli-configyaml-should-be-0600
=> fix(lk): correct cfg file permission check and bin name

cmd/lk/cloud.go, pkg/config/config.go
- Enable `lk cloud auth` for public use
- Use project names instead of device names for stored credentials
- Detect and prompt for duplicate project names
- Updated usage copy for `lk cloud auth`
=> chore(auth): cleanup copy, dedupe project names, and enable feature

cmd/lk/join.go, cmd/lk/room.go
Switch to the new `OnDataPacket` callback instead of the legacy `OnDataReceived`. Add flags for publishing DTMF and user data to `lk room join`. Legacy `lk join-room` still uses old callback and doesn't support new flags.
=> Send and receive DTMF in join command.

README.md, cmd/lk/cloud.go, version.go
- Readme instructions for `lk cloud auth`
- Fix bug when setting a just-authenticated project as default if its name was deduped
- Bump version to `2.1.0`
=> chore(lk): last looks for 2.1.0 release

cmd/lk/utils.go
The optional/hidden functions modify the original flag passed in rather than create their own copy. This ends up displaying the wrong options in the help menu for a command. For example, `lk room send-data` requires the `--room` flag, but running help on the command gives this:
```
NAME:
lk room send-data - Send arbitrary JSON data to client
USAGE:
lk room send-data [OPTIONS] DATA
OPTIONS:
--topic TOPIC                          TOPIC of the message
--identity value [ --identity value ]  One or more participant identities to send the message to. When empty, broadcasts to the entire room
--help, -h                             show help (default: false)
```
It also allows running the command itself, not raising that the `room` flag wasn't set.
=> Fix flags getting erroneously hidden or optional

cmd/lk/app.go, cmd/lk/cloud.go, go.mod, go.sum, pkg/bootstrap/bootstrap.go, version.go
- Minor cleanup around sandbox/bootstrap commands
- Bump version to `2.1.1`. Though you could consider this a `2.2.0-alpha.1`, it's easier to release this way for homebrew and winget.
=> chore(cmd): cleanup for sbx internal alpha

cmd/lk/app.go, cmd/lk/cloud.go, cmd/lk/main.go, cmd/lk/project.go, cmd/lk/style.go, cmd/lk/utils.go
- Reverts to using default terminal color palette, since branded colors do not always play nice with light terminal themes
- Adds hint text to guide users to start agent after install
=> feat(cmd): add next steps hint after template install

cmd/lk/app.go, pkg/bootstrap/bootstrap.go
Instead of taking the place of tools devs are already familiar with, just print out the steps for devs to run themselves.
```sh
tobiasfried@slate /tmp % lk app sandbox --id 5lfwjtkd6cy
Using default project [Atrium]
Cloning template...
Instantiating environment...
Running task post_create_sandbox...
To setup and run the agent:
cd /tmp/optimized-instance/agent
python3 -m venv venv
source venv/bin/activate
python3 -m pip install -r requirements.txt
python3 agent.py start
tobiasfried@slate /tmp %
```
=> feat(cmd): use written install instructions instead of automatic

cmd/lk/app.go, pkg/bootstrap/bootstrap.go
https://linear.app/livekit/issue/DEX-766/update-cli-to-support-template-compatibility
=> feat(sbx): unify app commands and support template compatibility

cmd/lk/app.go, version.go
...and tweak some sandbox prompt logic
=> chore(sbx): bump version

cmd/lk/app.go, cmd/lk/project.go, cmd/lk/utils.go, pkg/config/config.go, version.go
- unhide `lk app` subcommands
- allow referring to project by slug-names
=> feat(lk): refer to projects by slug-name

cmd/lk/project.go, version.go
`--project` accepts "Canonical names" as well as slug-names. Other project commands should follow the same semantics.
=> fix(cmd): set-default should work with slug-names too

cmd/lk/cloud.go
https://linear.app/livekit/issue/DEX-810/fail-gracefully-when-lk-cloud-auth-cannot-open-a-browser-window
It's okay if `lk cloud auth` can't open in a browser window. This is expected in Docker containers, and it is sufficient that we print the URL to do so manually.
=> fix(auth): allow opening browser to fail silently during auth

cmd/lk/cloud.go, cmd/lk/project.go, cmd/lk/utils.go, pkg/config/config.go
the rest of tooling is set to use the standard name. doing it on the reader path tend to create inconsistencies in behavior (for example set-default did not work for me)
=> Standardize safe names on project auth

cmd/lk/app.go, cmd/lk/utils.go
https://linear.app/livekit/issue/DEX-820/use-tmp-for-working-files-in-indeterminate-state
- Use `os.TempDir()` while files are in an indeterminate state (E.G. while bootstrapping a template repository), relocating them after to the desired path
- Better logging of unexpected errors during bootstrap
=> feat(lk): use tmp directory while preparing files

cmd/lk/app.go, cmd/lk/cloud.go, cmd/lk/egress.go, cmd/lk/ingress.go, cmd/lk/project.go, cmd/lk/proto.go, cmd/lk/replay.go, cmd/lk/room.go, cmd/lk/sip.go, cmd/lk/utils.go, cmd/lk/utils_test.go
All commands with structured data output typically printed as a table may now be printed to stdout as JSON by using the `--json` flag. We also suppress additional output some commands would print unless used with the `--verbose` flag, in order to keep the output valid JSON.
Resolves  #454
=> feat(cmd): allow tables to be output as json

cmd/lk/app.go, pkg/bootstrap/bootstrap.go
https://linear.app/livekit/issue/DEX-938/clean-up-additional-files-on-bootstrap
- Removes additional unneeded files when bootstrapping a template: `.git/` `taskfile.yaml`, `renovate.json`, `TEMPLATE.md`
=> chore(cmd): strip additional files when degitting

cmd/lk/app.go, pkg/bootstrap/bootstrap.go
- `lk app env` command is no longer hidden
- `lk app env` now prints to stdout instead of clobbering `.env.local` unexpectedly, but can be called with the `--write` flag to keep previous behavior
- `lk app env [DIR]` is now supported, allowing you tun run outside CWD
- We no longer print an error if a template cloned using `lk app create` does not contain a `taskfile.yaml`, it is now considered optional
NOTE: we no longer recursively search the whole project for `.env.example` files -- only in the root directory. This means that we don't support "meta templates" that stitch together other templates to make a full application stack, but we were not using it anyway, and prefer to direct users to bootstrap each component separately.
=> feat(cmd): better ergonomics around `lk app` and templates

README.md, cmd/lk/app.go, cmd/lk/project.go, cmd/lk/utils.go, cmd/lk/utils_test.go, pkg/bootstrap/bootstrap.go, version.go
- Bump version to `2.3.0`
- Add instructions for bootstrapping an app from template
- Prints template tags next to name when listing
- Adds `lk app list-templates` command, with table or `--json` output
- Shows default project with `*` instead of a whole table column dedicated to it
=> feat(docs+cmd): document bootstrap feature, add template list

cmd/lk/app.go, pkg/bootstrap/bootstrap.go
- `lk app env` can be run anywhere, when formerly it required a project directory with a `.env.example`
- when run without a default project or the `--project` flag, lets you pick the project for which to expand the environment
=> feat(cmd): expand project env from anywhere

cmd/lk/app.go, cmd/lk/cloud.go, cmd/lk/dispatch.go, cmd/lk/egress.go, cmd/lk/ingress.go, cmd/lk/join.go, cmd/lk/loadtest.go, cmd/lk/main.go, cmd/lk/project.go, cmd/lk/replay.go, cmd/lk/room.go, cmd/lk/sip.go, cmd/lk/token.go
https://linear.app/livekit/issue/DEX-1032/simplify-helpusage-by-removing-categories
https://linear.app/livekit/issue/DEX-1033/recognize-next-public-prefix-for-some-things
=> chore(cmd): remove categories from command usage

cmd/lk/app.go, pkg/bootstrap/bootstrap.go
I'm working on a swift example app for the voice assistant and it needs to get the sandbox ID loaded in, but none of the API keys. The Android example app [does this with a global variable](https://github.com/livekit-examples/android-voice-assistant/blob/main/taskfile.yaml) that gets overridden via `sed`, but the approach is brittle and a little messy. 
In Swift, the best approach is to use xcconfig files, which can be imported in as build settings. It turns out that xcconfig files basically have the same format as env files, so we can just treat them as the env files for this type and take advantage of our existing env-population code. The only issues are 
a) the files need to be in a subdirectory
b) it's best to give them the `.xcconfig` extension (although not strictly necessary, it …
=> Allow custom env file paths

pkg/bootstrap/bootstrap.go
previously the command just said `404 Not Found` and it wasn't obvious the problem was the sandbox param, vs the template param.
=> Add a clearer error message for invalid sandbox id

cmd/lk/app.go, cmd/lk/cloud.go, cmd/lk/dispatch.go, cmd/lk/egress.go, cmd/lk/ingress.go, cmd/lk/project.go, cmd/lk/proto.go, cmd/lk/replay.go, cmd/lk/room.go, cmd/lk/token.go, cmd/lk/utils.go, cmd/lk/utils_test.go, pkg/util/fs.go, pkg/util/json.go, pkg/util/strings.go, pkg/util/strings_test.go
https://linear.app/livekit/issue/DEX-1044/support-lk-app-create-when-run-from-non-boot-drive
- Fix failure to relocate files from `/tmp` (or equivalent) to permanent path when said path is on a different filesystem
- Move some utils to `pkg` and clean up some unused code
=> fix(cmd): relocate temp files across filesystem boundaries

cmd/lk/proto.go, cmd/lk/sip.go
Support SIP media encryption and allow overriding `CreateSIPParticipant` options with flags (and creating it without a JSON config file).
=> Support SIP media encryption

.github/bump-version.sh, .github/workflows/bump.yml, .nanparc
this PR adds [nanpa](https://github.com/nbsp/nanpa) tooling to LiveKit CLI. on every new PR that contains code changes, make sure to add a file at `/.nanpa/something.kdl`, detailing the change:
```
patch type="added" "Add foo to bar"
minor type="security" "Oops"
```
multiple changes can be added per file. a future version of nanpa will add a handy CLI for adding them, for now they need to be added by hand. see [Keep A Changelog](https://keepachangelog.com/en/1.1.0/#how) for valid types.
when the [GitHub app](https://github.com/nbsp/ilo) detects changes, it will open an issue detailing them. when it is closed, it will run CI to tag versions. a release still doesn't happen automatically, in case of any bugs — you have to make a release from the tag yourself.
i have added the sample …
=> nanpa: init at 2.3.1

.nanpa/2131758.kdl, cmd/lk/app.go, cmd/lk/cloud.go, cmd/lk/dispatch.go, cmd/lk/egress.go, cmd/lk/ingress.go, cmd/lk/join.go, cmd/lk/loadtest.go, cmd/lk/main.go, cmd/lk/project.go, cmd/lk/proto.go, cmd/lk/replay.go, cmd/lk/room.go, cmd/lk/token.go, cmd/lk/utils.go, go.mod, pkg/bootstrap/bootstrap.go, pkg/loadtester/loadtest.go, pkg/loadtester/loadtester.go
Make go mod version consistent with git tag so other projects can import the livekit-cli module.
=> Update module to v2

.nanpa/no-license.kdl, pkg/bootstrap/bootstrap.go
When a customer uses the bootstrap function to clone an example app, we intend to give them complete rights to the resulting code to basically do whatever they want.
By including the LICENSE file, we are actually causing them to apply it (whether intentional or not) if they publish it. So let's not copy it.
There's maybe a deeper issue worth considering which has to do with copyright. The Apache 2 license requires a copyright NOTICE in the repo as well as a copyright notice at the top of every source file. But it doesn't really make sense for us to copyright bootstrap templates in this way... It would be ideal if we could strip the copyright notices from the files as well or simply choose an even less restrictive license for our sample apps such as MIT.  And that could also be a …
=> Don't copy LICENSE or NOTICE files with bootstrap

pkg/loadtester/loadtest.go
In fact, err is incorrect and should be  `ctx.Err()`.
=> fix: fix the wrong error return value

.nanpa/project-config-subdomain.kdl, cmd/lk/agent.go, cmd/lk/utils.go, pkg/config/config.go
- more explicit path'ing and workdir for agent hosting commands
- add the subdomain project lookup to support agent hosting toml
- for agent hosting list command, add a project-id param to allow listing agents on projects other than the default project
=> add support for project lookup via subdomain

cmd/lk/agent.go, cmd/lk/utils.go, pkg/agentfs/build.go, pkg/agentfs/docker.go, pkg/agentfs/logs.go, pkg/agentfs/secrets-file.go, pkg/agentfs/tar.go, pkg/agentfs/utils.go
since we can use credentials both in form of projects or CLI/env var. it could be confusing which set is actually being used. users have inadvertently connected to the wrong projects because of an env var being set.
driveby: also added copyright headers
=> log message when using url/keys from environment.

cmd/lk/room.go, version.go
Long flag forms were being shadowed by short variants in some commands, leading to incorrect parsing in `lk room mute-track`, `lk room update-subscriptions`.
https://linear.app/livekit/issue/DEVM-567/fix-unmute-issue-with-long-option-in-lk-command
=> fix(room): corrects behavior of room commands with short arg variants

.nanpa/agent-hosting-uploads.kdl, pkg/agentfs/tar.go, pkg/agentfs/tar_test.go
this fixes the tarball create issues with symlinks
```
failed to walk directory: failed to copy file content for res/agent_male.png: current number exceeds max
```
=> fix symlink file handling and add tests for tarball create

.nanpa/dev-flag.kdl, cmd/lk/utils.go
This change adds `--dev` flag that uses the same credentials as LiveKit server's `--dev` flag.
=> Add a flag for using dev credentials

cmd/lk/agent.go, cmd/lk/main.go, pkg/agentfs/config-file.go
`livekit.toml` now supports `cpu` values of ints and floats too. I tripped up on it once before and it seems awkward not to.
=> feat(agents): support int and float cpu cfg values

cmd/lk/utils.go
Convert URL to http for curl printer. So far, for _curl_ printer, e.g.:
```
livekit-cli --curl sip in list 
```
we get following incorrect (unsupported protocol) curl command:
```
curl -X POST wss://my-project.livekit.cloud/twirp/livekit.SIP/ListSIPInboundTrunk
> `curl: (1) Protocol "wss" not supported`
```
=> ToHttpURL for curl printer

cmd/lk/agent.go, pkg/bootstrap/bootstrap.go
https://linear.app/livekit/issue/HA-95/secret-file-required-even-when-providing-secrets
Fix logic around agent secrets:
- None required for `lk agent deploy`
- Use lazy exaluation if secrets set via flags in `lk agent update-secrets`
=> fix(agents): correct logic for agents secrets flags

cmd/lk/app.go, pkg/config/config.go, pkg/util/url.go, version.go
Fixes [this issue](https://github.com/livekit-examples/voice-assistant-frontend/issues/114) in which project credentials were required to bootstrap. We now defer until after cloning the template to check for project credentials, and if you opt not to use any local ones or to auth with a browser, we simply allow you to progress and prompt you to enter `LIVEKIT_` variables manually (which can also be left empty).
=> fix(app): allow bootstrapping of templates without authenticating

cmd/lk/agent.go, cmd/lk/app.go, cmd/lk/utils.go, pkg/agentfs/secrets-file.go, pkg/config/livekit.go
Fixes an issue in #569 in which invalid config files were silently ignored
=> fix(lk): fail early if config file is present and invalid

Dockerfile, version.go
Docker deploy failing because go toolchain was bumped in `go.mod` but not in Dockerfile
=> fix(ci): go version in dockerfile should match go.mod

cmd/lk/agent.go, pkg/agentfs/build.go, pkg/agentfs/logs.go, pkg/config/livekit.go
All hosted agents are identified via unique ID instead of user-defined name.
* Use agent ID for all hosted agent API.
* Automatically update livekit.toml file with agent ID.
=> Deprecate hosted agent name from config

cmd/lk/agent.go, cmd/lk/app.go, cmd/lk/sip.go, pkg/agentfs/utils.go
- `lk sip` commands now work with automatic project auth flow if unauthenticated
- `lk agent list` and `lk agent versions` now sort entries by reverse-chronological order
```
> lk agent list
┌─────────────────┬─────────┬────────────────┬──────────────────────┐
│ ID              │ Regions │ Version        │ Deployed At          │
├─────────────────┼─────────┼────────────────┼──────────────────────┤
│ CA_xqxVnfLfH5sh │ us-east │ 20250723055127 │ 2025-07-23T05:51:30Z │
│ CA_JcXevr5Anw6Z │ us-east │ 20250718215738 │ 2025-07-18T21:57:39Z │
└─────────────────┴─────────┴────────────────┴──────────────────────┘
```
```
> lk agent versions
┌────────────────┬─────────┬──────────────────────┐
│ Version        │ Current │ Created At           │
├────────────────┼─────────┼──────────────────────┤
│ …
```
=> fix(agents+sip): address some style and usability issues

pkg/agentfs/tar.go, pkg/agentfs/tar_test.go
Ignore `.env.*` instead of `*.env` for cloud agents
Context: https://live-kit.slack.com/archives/C08HHUXHAKA/p1753727983216529?thread_ts=1753699955.554379&cid=C08HHUXHAKA
=> Ignore `.env.*` instead of `*.env` for cloud agents

cmd/lk/agent.go, cmd/lk/room.go, cmd/lk/utils.go, pkg/agentfs/secrets-file.go
https://linear.app/livekit/issue/HA-243/fix-secrets-parsing-when-encountering-special-characters-in-secret
Improve parsing of `--secrets` flag (and other `StringSlice`-based key-value arguments) by parsing them properly with `godotenv`. Previously we used a naive method of splitting on "=" character, but this is insufficient for things like base64 encoded secrets, inline TOML, and anything with that character as part of a secret.
A downside of this approach is that we can no longer use built-in CSV splitting, so a command like this:
```
lk agent update-secrets --secrets 'foo=yes,bar=42'
```
Now has to be passed as multiple arguments:
```
lk agent update-secrets \
--secrets 'foo=yes' \
--secrets 'bar=42'
```
An upside is that we can support inline JSON:
```
lk agent update-secrets …
```
=> fix: make secrets and other kv arg parsing more rubust

cmd/lk/agent.go, version.go
- Allow user to select existing Agent ID if not provided in `lk agent config`
- Respects `workingDir` when creating config file
- Bump version
=> chore(agents): fallback to agent selector when generating config

pkg/agentfs/docker.go, pkg/agentfs/examples/python.pip.Dockerfile, pkg/agentfs/examples/python.uv.Dockerfile
Fix expansion of the `PROGRAM_MAIN` variable in python Dockerfile templates by using native Golang string templates. This vastly simplifies the previous entrypoint detection we were doing previously.
Have tested this with both a `pip` and `uv` project locally, as well as with cloud deployments and it works 👍
=> fix(agents): correctly expand `PROGRAM_MAIN` in Dockerfiles

pkg/agentfs/examples/python.pip.Dockerfile, pkg/agentfs/examples/python.uv.Dockerfile
some Agents extra dependencies (like aws realtime) require Python 3.12+ we shouldn't need to ship with older versions of Python
=> chore: update to Python 3.13 in default Docker templates

cmd/lk/agent.go, pkg/agentfs/docker.go, pkg/agentfs/utils.go
While testing #646 I made a couple updates that deserved their own PR
=> Add generate dockerfile command

pkg/agentfs/docker.go, pkg/agentfs/tar.go, pkg/agentfs/utils.go, pkg/util/fs.go, version.go
https://linear.app/livekit/issue/HA-270/make-sure-file-paths-in-agent-commands-account-for-os-specific-path
Detected agent entrypoint should always be normalized to a Unix path before inserting into Dockerfile template.
So should the relative paths of files appended to tarball during upload.
=> fix(agents): convert agent entrypoints to unix path before templating

pkg/agentfs/docker.go, version.go
RE: #683, we should not use `filepath.Join()` to locate embedded dockerfiles, since `embed.FS` uses unix-style path separators on all platforms. Instead, construct the path manually.
See: github.com/golang/go/issues/45230
=> fix(agents): fix failure to generate dockerfiles on windows

cmd/lk/replay.go, go.mod, go.sum
[This commit](https://github.com/livekit/protocol/commit/29a3acafc6d1de32a5db187facc6734e2a777257#diff-00dee1f457993c0240080184602c17b42f8ba8a63d62219aaa62216840988cccR13-R18) seems to have changed a few things.
=> Fixing replay after protocol dep bump

version.go
major version 2.6.0 that supports livekit-cli version header
=> bump major version

cmd/lk/agent.go, cmd/lk/app.go, cmd/lk/cloud.go, cmd/lk/project.go, cmd/lk/utils.go, pkg/bootstrap/bootstrap.go, pkg/config/config.go, version.go
https://linear.app/livekit/issue/DPRO-491/cli-focused-onboarding-spike-and-all-hands-demo
- Adds `lk agent init` command, which automatically gives the cloned template an agent name, creates a sandbox, sets up explicit dispatch for it, and prints its URL on completion
- If authenticating your first project via CLI, automatically make it the default project
DEPENDS ON: https://github.com/livekit/cloud-api-server/pull/1311 and, indirectly, https://github.com/livekit-examples/agent-starter-python/pull/25
If you want to test it now, you'll have to test against staging API and a dummy agent template:
```
lk agent init \
--server-url https://cloud-api-server-public.ochicago1a.staging.livekit.app \
--dashboard-url https://cloud.staging.livekit.io \
--template-url …
```
=> feat(agents): add streamlined lk agent init command

cmd/lk/agent.go, pkg/agentfs/build.go, pkg/agentfs/client.go, pkg/agentfs/logs.go
`livekit-cli` is the source of truth for the cloud-agents API client, and other callers should import it from there. Version enforcement will be based on the livekit-cli version.
This PR refactors livekit-cli to make its functionality easier to share with other callers.
ref HA-298
=> Refactor for shared cloud agents lib
