livekit/livekit-cli

.github/workflows/release.yml

You can see the result at https://github.com/cmaster11/livekit-cli/releases

GitHub action to automatically build and release binaries for the CLI

---

cmd/livekit-cli/egress.go
cmd/livekit-cli/join.go
go.mod
go.sum

`livekit-cli test-egress-template --base-url https://recorder.livekit.io/\# --layout speaker-dark --publishers 4`

template tester

---

cmd/livekit-cli/room.go

`livekit-cli update-room-metadata --room <name> --metadata <metadata>`

Add sub-command to update room metadata

---

cmd/livekit-cli/egress.go
pkg/loadtester/loadtest.go
pkg/loadtester/loadtester.go
pkg/loadtester/loadtestprovider.go

Also increasing variety of videos being sent.

Fixed egress launch template tester

---

.gitignore
.goreleaser.yaml
Makefile
autocomplete/bash_autocomplete
autocomplete/fish_autocomplete
autocomplete/zsh_autocomplete
cmd/livekit-cli/main.go
install-cli.sh

shell autocomplete functions

---

cmd/livekit-cli/loadtest.go
pkg/loadtester/loadtest.go

> Contexts should not be stored inside a struct type, but instead passed to each function that needs it.
https://go.dev/blog/context-and-structs

Refactor load test for better use of context

---

README.md

Refs https://github.com/livekit/livekit-cli/issues/132

docs: document --simulate-speakers

---

.github/workflows/build.yaml
cmd/livekit-cli/ingress.go
go.mod
go.sum
pkg/loadtester/util.go

This is from a community report. Getting a nil state object is unexpected, and something else is likely wrong in the setup, but we should be defensive here.

Check for the existence of the ingress State object before accessing it

---

cmd/livekit-cli/egress.go
go.mod
go.sum

Also providing more information in list-egress table

Improved list-egress and stop-egress to support batching

---

cmd/livekit-cli/main.go
cmd/livekit-cli/sip.go
go.mod
go.sum

Create, List and Delete for Trunk, Dispatch Rule and Participant

Add SIP Commands

---

Makefile
cmd/livekit-cli/room.go
version.go

* max-playout-delay
* empty-timeout
* departure-timeout

Added more options to CreateRoom API.

---

cmd/livekit-cli/sip.go
go.mod
go.sum

Requires https://github.com/livekit/protocol/pull/696

Update SIP protocol, print new metadata.

---

cmd/lk/egress.go
cmd/lk/ingress.go
cmd/lk/project.go
cmd/lk/proto.go
cmd/lk/replay.go
cmd/lk/sip.go
cmd/lk/style.go
cmd/lk/utils.go
go.mod
go.sum

- Removes `olekukonko/tablewriter` dependency in favor of `charmbracelet/lipgloss`, which was already a transitive dependency of ours
- Some general tidying of style and rendering
BEFORE / AFTER:

feat(cmd): snazzy new tables

---

cmd/lk/cloud.go
cmd/lk/utils.go

Depends: https://github.com/livekit/cloud-api-server/pull/747/

fix(auth): use hashed secret as identity to verify token authenticity

---

cmd/lk/app.go
pkg/bootstrap/bootstrap.go

Implements the `lk app sandbox --id XXXXXX` cmd

feat(sbx): add init sandbox command

---

cmd/lk/app.go

Passing sandbox ID into env replacer unlocks cool stuff like custom agent dispatch to a specific sandbox

feat(sbx): allow sandbox to replace additional environment variables

---

cmd/lk/project.go
cmd/lk/utils.go

lipgloss changed the row numbering in this PR (https://github.com/charmbracelet/lipgloss/pull/377)

Fix header row style.

---

pkg/loadtester/loadtest.go
version.go

- Bump version for release
- Don't print empty `load-test` tables

chore(cmd): bump version

---

version.go

seeing some version report issue in https://github.com/Homebrew/homebrew-core/pull/207543, bump version to match with the release.
cc @cnderrauber

fix: bump version to 2.3.3

---

cmd/lk/agent.go
go.mod
pkg/agentfs/secrets-file.go
version.go

Various improvements to `lk agents` flows:
- Better ergonomics around some commands, prompt for missing values
- Consistent application theme
- Fixed some erroneous early returns and errors

chore(agents): streamline some command interactions and minor bugs

---

cmd/lk/agent.go

Use table and date formatting consistent with other commands in `lk agent` commands.

chore(agents): consistent table style and formatting

---

cmd/lk/agent.go

This PR adds support for streaming hosted agent build logs

Add support for streaming hosted agent build logs

---

cmd/lk/agent.go
cmd/lk/app.go
cmd/lk/utils.go
pkg/util/action.go

- Re-create agent client if custom project selection is used

fix(agents): re-create agent client after project selection

---

version.go

Will release on Tuesday (May 20, 2025)

chore(lk): bump version for release

---

cmd/lk/agent.go

...we checked `innerErr != nil` which was not set.

Fix innerErr in requireDockerfile

---

cmd/lk/project.go

fix(project): propagate context after determining correct project

---

version.go

Bump version to support X-LIVEKIT-CLI-VERSION header
ref HA-298

bump version
